# Generated by Django 3.0.5 on 2020-05-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Event'},
        ),
        migrations.AlterModelOptions(
            name='meetingminutes',
            options={'verbose_name_plural': 'MeetingMinutes'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resource'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='MeetingMinutes',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='Resource',
        ),
    ]
