# Generated by Django 3.0.5 on 2020-05-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0002_auto_20200516_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'meetings'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='MeetingMinute',
        ),
    ]
